### ISSUE TITLE
Spin 3.0 Documentation Toggle

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/developer#1383]
spin.fermyon.dev has a drop down for docs for 1.x and 2.x. We should track and consider a new drop down item. Here are the changes @karthik2804 made to add the 2.x docs: https://github.com/fermyon/developer/pull/993

**Comment by karthik2804** [comment]
We may also want to consider dropping 1.0 maybe?

**Comment by fibonacci1729** [comment]
@karthik2804 is there a compelling reason to drop v1.0?

**Comment by karthik2804** [comment]
Well, it is not a very strong opinion, but the size of the app will grow, slowing things like the Link checker and indexing the pages (which should not be a big issue since we do not have a blog-like view).

The intention there was to check if we were going to support the older versions. Happy to keep the version though.
