### ISSUE TITLE
Spin docs: Ability to toggle between dev/unreleased and latest

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#195]
I'm wondering if we need/want the functionality in the Spin docs to be able to delineate between unreleased features (meaning, on the `main` branch and included in `canary`, but not in an official semver release) and features/functionality included in the most recent release.

I suppose this could be accomplished via functionality built into the website itself (like a toggle between versions)... or maybe relegated to process/awareness, i.e. broadcast that canary.developer.fermyon.com is auto-deployed with the latest docs, potentially including unreleased features but that developer.fermyon.com is only updated when a semver tag in Spin is cut.  This latter route may be tricky (but not unsolveable), as it involves events that span multiple repos (we'll want to track when tags are pushed to fermyon/spin; this repo itself doesn't yet utilize tags, etc.)

Assuming this repo is going to grow to hold docs for other tools (eg Bartholomew), the same approach would apply to multiple repos, so we'll want to pick a strategy with this in mind.

**Comment by radu-matei** [comment]
cc @flynnduism, who has experience doing this for other project documentation websites.

**Comment by flynnduism** [comment]
Whatever approach is taken for channels, will probably impact on docs for supporting versions/releases too, it's hard to know if we will want to support Docs for all versions, but given this Developer docs repo will house many projects, we should consider how to accommodate such things. 

On various OSS project Docs I'm familiar with the approach was to spin off the [release tags](https://github.com/fermyon/spin/tags) and deploy them as a archival branch of the docs, and deploy each as static archive, with the subdomains mirroring the branch names.

e.g.
```
https://docs.projectname.io/                > main branch
https://release-v1-2.docs.projectname.io/   > v1.2
https://release-v1-1.docs.projectname.io/   > v1.1
```

### Content Structure

Our url structure is different here, given how we're housing many projects so I'm not sure what way makes the most sense - we probably need to incorporate subdirectories rather than subdomains, e.g. 

```
https://developer.fermyon.com/latest/spin/index
https://developer.fermyon.com/0.2/spin/index
https://developer.fermyon.com/0.1/spin/index
```

I've seen massive repos where all the versions co-exist as directories (rather than branches served individually), it presents other challenges, around SEO indexing and in-site docs search tools, and how internal links work when you have versions in the path - you have be careful how things are surfaced. It's easy to end up with scenarios where users end accidentally navigating between versions and it becomes a UX nightmare. 

<img width="135" alt="Screen Shot 2022-12-05 at 10 51 29 PM" src="https://user-images.githubusercontent.com/686194/205842048-afd5eee4-4e22-48c6-af6b-7f318e3f0f7e.png">

You search for Getting Started on latest, do you get 4 results for Getting Started 1.0, 2.0, 3.0 etc? Or if you don't index other versions, if you're a user on an older version search keeps taking you back to latest. 

### Front-end UI

In the website layout, the main changes are simple enough -

* add a dropdown to the menu to facilitate switching between the versions
* add a big sticky banner across the site reminds you that you are currently viewing version X.Y. (for any version that is any version/channel that is not the latest stable release)

**Comment by tpmccallum** [comment]
See linear.app's Developer Docs team for more information.

**Comment by flynnduism** [comment]
> See linear.app's Developer Docs team for more information

Is it possible to link to where it moved to? The Developer Docs team isn't visible by default, so we cannot access things there.
