### ISSUE TITLE
Unable to add (change) css

### ISSUE THREAD

**Issue by mabushey** [fermyon/developer#546]
I would like to style code blocks (three backticks in MarkDown) but I can't get any CSS to work right.
Ideally I would like to include it in the page, otherwise the blog template would work.

In `templates/content_top.hbs`, I added `<link href="/static/pre.css" rel="stylesheet">` under the bootstrap link.

It seems like once something is there, it's permanently cached, changing the CSS (static/pre.css) makes no further difference. Currently I have a different background color in Opera, but not in Firefox. Changing the background color or any of the CSS does not change anything in the browser. I've deleted the `.spin` dir, but that looks like it's only logs.

As a work around, if I rename `static/pre.css` to `static/pre2.css` and update the link in `content_top.hbs` I can get a change.

**Comment by tpmccallum** [comment]
Hi @mabushey 
The `.css` files themselves are actually machine-generated.
Have you seen the developer documentation regarding updating CSS?
https://developer.fermyon.com/common/contributing-docs#63-how-to-properly-edit-css-styles
Please let me know if the above link solves your question. If not, please reply here, and I can help you get to a point where you can successfully create your custom changes.

**Comment by karthik2804** [comment]
Hello @mabushey - Thanks for reporting this. I just noticed that the static file server used in that template is pretty old and used to have a cache period of 1 year. This has been fixed in recent releases. You can grab the latest `wasm` module release from https://github.com/fermyon/spin-fileserver/releases/tag/v0.0.2 . Replacing the `spin_static_fileserver.wasm` with the latest release should fix the issue. The latest release has a cache period of 1 minute. You could also set a cache period of 0 seconds by setting an environment variable in `spin.toml` by adding a new line after line 17 with the following content.

```toml
environment = {CACHE_CONTROL = "max-age=0" }
```

I am also working on updating the template site with the latest modules which I should PR a bit later today if you would prefer to wait for that.

**Comment by mabushey** [comment]
Thanks for very quickly responding. In the docs, it says /static is where you put .css files. I see no place for .scss files, which makes me happy. I'm not a themer, I have no interest in the overhead of scss or the insanity known as npm. If absolutely required I could run npm in a docker container. Am I forced to use scss? If so, can sass be used instead? There are a few Rust implementations to get around needing the npm nightmare. What you linked me to doesn't really seem like it's for bart, and nowhere in the Bart docs is scss referenced, other than specifically for the fermyon website.

**Comment by karthik2804** [comment]
@mabushey The quick fix would be to just swap out to a later release of the `spin_file_server` and/or use hard refresh to invalidate the cache. Optionally use "incognito" mode as that should not be caching stuff.

**Comment by mabushey** [comment]
Hitting F5 for a refresh did not update anything. I added `max-age=0` to `spin.toml` and things seem to be more managable now. Thanks!

**Comment by karthik2804** [comment]
Glad that solved your issue. You would need to do a hard refresh (it clears your cache). The shortcut for it depends on the browser and operating system. For example on Linux, it is `ctrl+shift+r` on chrome.
