### ISSUE TITLE
Spin Quickstart has different 'Hello' messages for different languages 

### ISSUE THREAD

**Issue by sohanmaheshwar** [fermyon/developer#689]
Minor issue:

The Hello messages in the [Spin Quickstart](https://developer.fermyon.com/spin/quickstart) guide are different for different languages:

- `Hello, Fermyon` for Rust
- `Hello from TS-SDK` for Typescript
- `Hello from the Python SDK` for Python
- `Hello Fermyon!` for TinyGo

And final code block for the `$ curl -i localhost:3000` is `Hello, Fermyon`

I'd suggest going with a standard approach for all. I can make the change and submit the PR based on what the decision is.

**Comment by itowlson** [comment]
The text comes from the various language templates so this would need to be fixed at source.  If we go for a per-language convention (e.g. "Hello from Rust") then we would need to clarify that the curl output would vary.

**Comment by sohanmaheshwar** [comment]
For the `curl` output - Should we have the different tabs for different languages? Like we do for the earlier code snippets?

**Comment by itowlson** [comment]
We _could_, but then we add visual clutter and risk giving the impression that how you run Spin depends on your source language.  But it does maybe point to using a standard phrase ("Hello, Fermyon" or "Hello from Spin" or whatever) rather than mentioning the language/SDK name.

Incidentally, if we're tweaking the template response then can we get rid of that absurd foo/bar header and put something meaningful like `Content-Type: text/plain` instead #badattitude

**Comment by sohanmaheshwar** [comment]
Spoke with @mikkelhegn and we thought for now we could just clarify that `curl` output will vary. 

Eventually we can use standard phrases in the SDK. Its just that I'm not sure if there are dependencies i.e other docs where outputs are listed as 'Hello from TS-SDK' et al. 

Created a PR here: https://github.com/fermyon/developer/pull/700
