### ISSUE TITLE
Docs(v2): update snippets/examples to use manifest v2

### ISSUE THREAD

**Issue by vdice** [fermyon/developer#957]

**Comment by vdice** [comment]
Note: I'm also seeing manifest snippets in `content/cloud` which doesn't have a v2 delineation.  What is our strategy/timing for updating these @tpmccallum @itowlson?

(Will continue under `content/spin/v2` in the meantime...)

**Comment by tpmccallum** [comment]
Great question @vdice 
@mikkelhegn is going to tackle this in two stages.

Stage 1 is to update manifest examples in `/spin/v2/` pages in a separate PR that we can merge now (asap); non-breaking because the `v2` files have future publish in frontmatter.
Re: https://www.notion.so/fermyon/Update-Manifests-examples-and-spin-new-examples-in-v2-pages-not-v1-legacy-folder-a1bb35329b9d4863b4f2ec434b71ea9f?pvs=4

Stage 2 is to update manifest examples in `/cloud/` pages in a separate PR that we can merge as part of the flip-switch at announcement time < https://www.notion.so/fermyon/Update-Manifests-examples-and-spin-new-examples-in-Cloud-pages-not-v1-legacy-folder-d1e098f24cfe45768aa156b1deb6bbe3?pvs=4 >

The examples in `v1` will just remain as is for correctness relative to Spin 1.x
